#!/bin/zsh

mkdir binutils-build
mkdir binutils-install
cd binutils-build
../binutils-${V_BINUTILS}/configure \
    --host=i686-w64-mingw32 \
    --prefix=/c/Users/Public/ev3dev \
    --target=arm-ev3dev-linux-gnueabi \
    "--with-pkgversion=GNU Binutils for ev3dev" \
    --enable-poison-system-directories \
    --with-sysroot=/c/Users/Public/ev3dev/arm-ev3dev-linux-gnueabi \
    --enable-plugins \
    --disable-nls \
    --enable-lto \
    --with-build-sysroot=/usr/local/arm-ev3dev-linux-gnueabi
make -j3
DESTDIR=$PWD/../binutils-install make install
cd ../binutils-install
