#!/bin/zsh
source ../versions.sh


mkdir -p sysroot-install/c/Users/Public/ev3dev/arm-ev3dev-linux-gnueabi
mv sysroot-libc-linux/{usr,lib} sysroot-install/c/Users/Public/ev3dev/arm-ev3dev-linux-gnueabi/

