#!/bin/zsh

mkdir gdb-build
mkdir gdb-install
cd gdb-build
../gdb-${V_GDB}/configure \
    --target=arm-ev3dev-linux-gnueabi \
    --prefix=/usr/local \
    --with-pkgversion='GDB for ev3dev' \
    --disable-nls \
    --with-libexpat \
    --datadir=/usr/local/share/ev3dev \
    --with-system-gdbinit=/usr/local/share/ev3dev/gdb/gdbinit \
    --with-sysroot=/usr/local/arm-ev3dev-linux-gnueabi/ \
    --enable-lto \
    || exit $?
make || exit $?
DESTDIR=$PWD/../gdb-install make install|| exit $?
cd ../gdb-install
cp ../../patches/gdb/gdbinit usr/local/share/ev3dev/gdb/gdbinit

